version: "3"
services:
    elasticsearch:
        image: "docker.elastic.co/elasticsearch/elasticsearch:7.2.0"
        environment:
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
            - "discovery.type=single-node"
        ports:
            - "9200:9200"
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data

    kibana:
        image: "docker.elastic.co/kibana/kibana:7.2.0"
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch

    filebeat:
        build: ./filebeat
        container_name: filebeat
        volumes:
            - /var/lib/docker/containers:/usr/share/dockerlogs/data:ro
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - logstash
        depends_on:
            - logstash

    logstash:
        build: ./logstash
        volumes:
            - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
            - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
        ports:
            - "5000:5000/tcp"
            - "5000:5000/udp"
            - "9600:9600"
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        depends_on:
           - elasticsearch
volumes:
    elasticsearch_data:
